package br.com.ufpb.dcx.si.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "PLACEHOLDER_ECOM_LIVROS_TABLE_NAME")
public class Livro {

	private String id;
	private String titulo;
	private String autor;
	private int edicao;

	public Livro() {
		// TODO Auto-generated constructor stub
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBRangeKey(attributeName = "titulo")
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitle(String titulo) {
		this.title = titulo;
	}

	@DynamoDBAttribute(attributeName = "autor")
	public String getAutor() {
		return this.autor;
	}

	public void setAuthor(String autor) {
		this.author = autor;
	}

	@DynamoDBAttribute(attributeName = "edicao")
	public int getEdicao() {
		return this.edicao;
	}

	public void setEdition(int edicao) {
		this.edition = edicao;
	}

	public String toString() {
		return String.format("Livro [id=%s, titulo=%s, autor=%s, edicao=%d]", this.id, this.titulo, this.autor,
				this.edicao);
	}
}
